# target : execution
# syntax -> make target
# ldflags for linking process


flags=-Wall -02 -std c2x
ldflags=

# make file for tree
all : tree

tree : tree.o
	cc ${flags} $^ -o $@ ${ldflags} 

tree.o : tree.c
	cc ${flags} -c $^

clean : 
	rm -f *.o tree